Repository PowerShell/PSScriptAnalyzer, pull requests merged in 2018-05, with the labels that each got.

#987 Add Docker images that work with PSSA to ReadMe and give examples
  README.md
Labels: Area - Documentation

#983 Scripts needed to build and sign PSSA via MS VSTS so it can be published in the gallery
  Utils/ReleaseMaker.psm1
  tools/releaseBuild/Image/DockerFile
  tools/releaseBuild/Image/buildPSSA.ps1
  tools/releaseBuild/Image/dockerInstall.psm1
  tools/releaseBuild/build.json
  tools/releaseBuild/signing.xml
  tools/releaseBuild/updateSigning.ps1
  tools/releaseBuild/vstsbuild.ps1
Labels: Area - Build, in progress

#980 Fix table of contents
  README.md
Labels: Area - Documentation

#990 Add NanoServer Docker example and summarize all docker examples better
  README.md
Labels: Area - Documentation

#957 Allow TypeNotFound parser errors
  Engine/ScriptAnalyzer.cs
  Engine/Strings.Designer.cs
  Engine/Strings.resx
  NuGet.Config
  Tests/Engine/InvokeScriptAnalyzer.tests.ps1
  tools/appveyor.psm1
Labels: Area - Engine

#925 Do not trigger UseDeclaredVarsMoreThanAssignment for variables being used via Get-Variable
  Rules/UseDeclaredVarsMoreThanAssignments.cs
  Tests/Rules/UseDeclaredVarsMoreThanAssignments.tests.ps1
Labels: Area - Rules

#969 AvoidDefaultValueForMandatoryParameter triggers when the field has specification: Mandatory=value and value!=0
  Rules/AvoidDefaultValueForMandatoryParameter.cs
  Tests/Rules/AvoidDefaultValueForMandatoryParameter.tests.ps1
Labels: in progress

#999 Added Chocolatey Install help
  README.md
Labels: Area - Documentation

#996 Fix New-Release cmdlet by also building also for v4 and misc. improvements
  Utils/ReleaseMaker.psm1
  build.ps1
Labels: Area - Build

#1002 Remaining release notes and version update to 1.17.0
  CHANGELOG.MD
  Engine/Engine.csproj
  Engine/PSScriptAnalyzer.psd1
  README.md
  Rules/Rules.csproj
Labels: Area - Build
