Repository PowerShell/PSScriptAnalyzer, pull requests merged in 2019-06, with the labels that each got.

#1178 Speedup cold runs of PSSA by using a runspace pool and parallelizing the slowest rule (AvoidAlias)
  Engine/CommandInfoCache.cs
  Engine/Helper.cs
Labels: Area - Engine

#1244 Update PossibleIncorrectComparisonWithNull documentation with better example
  RuleDocumentation/PossibleIncorrectComparisonWithNull.md
Labels: Area - Documentation

#1253 update signing file for versioned location of module
  tools/releaseBuild/FileCatalogSigning.xml
  tools/releaseBuild/signing.xml
Labels: Area - Build

#1246 -SaveDscDependency on Linux
  Engine/Generic/ModuleDependencyHandler.cs
  Tests/Engine/InvokeScriptAnalyzer.tests.ps1
  Tests/Engine/ModuleDependencyHandler.tests.ps1
Labels: Area - DSC

#1235 Prevent PSCloseBrace crash if hashtable definition start on first token and there is a PSCloseBrace violation
  Rules/PlaceCloseBrace.cs
  Tests/Rules/PlaceCloseBrace.tests.ps1
Labels: Area - Formatter, Issue - Bug

#1256 Make it possible to build ScriptAnalyzer with PowerShell7
  build.ps1
  build.psm1
Labels: Area - Build

#1258 Lock calls around Test-ModuleManifest, which is not thread safe
  Engine/Helper.cs
Labels: Issue - Bug

#1255 UseCorrectCasing: Do not correct applications or script paths at all
  Rules/UseCorrectCasing.cs
  Tests/Rules/UseCorrectCasing.tests.ps1
Labels: Area - Formatter, Issue - Bug

#1259 CHANGELOG for 1.18.1
  CHANGELOG.MD
Labels: Area - Documentation

#1263 Actionabilize errors from incorrect settings files
  Engine/Commands/InvokeScriptAnalyzerCommand.cs
Labels: Area - Engine

#1272 Update documentation for parameter "Settings" of command "Invoke-ScriptAnalyzer" to include the key "RecurseCustomRulesPath"
  docs/markdown/Invoke-ScriptAnalyzer.md
Labels: Area - Documentation
