Repository PowerShell/PSScriptAnalyzer, pull requests merged in 2020-05, with the labels that each got.

#1494 Make .Net Core version in Docker image of .devcontainer match the one in global.json
  .devcontainer/Dockerfile
Labels: Area - Build

#1498 UseConsistentWhitespace: Fix CheckParameter bug when using interpolated string
  Rules/UseConsistentWhitespace.cs
  Tests/Rules/UseConsistentWhitespace.tests.ps1
Labels: Area - Formatter, Area - Rules, Issue - Bug

#1493 UseUsingScopeModifierInNewRunspaces: Fix ArgumentException when the same variable name is used in 2 different sessions.
  Rules/UseUsingScopeModifierInNewRunspaces.cs
  Tests/Rules/UseUsingScopeModifierInNewRunspaces.tests.ps1
Labels: Area - Rules, Issue - Bug

#1509 ReadMe: Remove reference to Windows PowerShell in Introduction
  README.md
Labels: Area - Documentation

#1499 Add more useful launch configurations
  .vscode/launch.json
Labels: Area - Build
