Repository PowerShell/PSScriptAnalyzer, pull requests merged in 2020-01, with the labels that each got.

#1387 Remove obsolete GetCommandInfoLegacy method and use GetCommandInfo instead
  Engine/CommandInfoCache.cs
  Engine/Helper.cs
  Rules/UseCmdletCorrectly.cs
  Rules/UseShouldProcessCorrectly.cs
Labels: Area - Build

#1388 Use .net core sdk 3.1
  README.md
  global.json
Labels: Area - Build

#1389 Update SuppressMessageAttribute docs link and use single quotes in examples
  README.md
Labels: Area - Documentation

#1392 Remove redundant whitespace between parameters with new option (disabled by default) in UseConsistentWhitespace
  Engine/Settings/CodeFormatting.psd1
  Engine/Settings/CodeFormattingAllman.psd1
  Engine/Settings/CodeFormattingOTBS.psd1
  Engine/Settings/CodeFormattingStroustrup.psd1
  RuleDocumentation/UseConsistentWhitespace.md
  Rules/Strings.Designer.cs
  Rules/Strings.resx
  Rules/UseConsistentWhitespace.cs
  Tests/Rules/UseConsistentWhitespace.tests.ps1
Labels: Area - Formatter

#1382 New rule - ReviewUnusedParameter
  RuleDocumentation/README.md
  RuleDocumentation/ReviewUnusedParameter.md
  Rules/ReviewUnusedParameter.cs
  Rules/Strings.Designer.cs
  Rules/Strings.resx
  Tests/Engine/GetScriptAnalyzerRule.tests.ps1
  Tests/Rules/AvoidAssignmentToAutomaticVariable.tests.ps1
  Tests/Rules/AvoidPositionalParameters.tests.ps1
  Tests/Rules/ReviewUnusedParameter.tests.ps1
Labels: Issue - New Rule

#1394 Add more automatic variables to PSAvoidAssignmentToAutomaticVariables that are not read-only but should still not be assigned to in most cases
  Rules/AvoidAssignmentToAutomaticVariable.cs
  Rules/Strings.Designer.cs
  Rules/Strings.resx
  Tests/Rules/AvoidAssignmentToAutomaticVariable.tests.ps1
Labels: Issue - Enhancement

#1390 Use latest version of PlatyPS in AppVeyor
  README.md
  tools/appveyor.psm1
Labels: Area - Build

#1358 Increase maximum runspace pool size in flaky test
  Tests/Engine/Helper.tests.ps1
Labels: Area - Build

#1391 Correct casing of parameters as well in PSUseCorrectCasing formatter rule
  RuleDocumentation/UseCorrectCasing.md
  Rules/Strings.Designer.cs
  Rules/Strings.resx
  Rules/UseCorrectCasing.cs
  Tests/Rules/UseCorrectCasing.tests.ps1
Labels: Area - Formatter

#1398 Update adopters file with entry for Microsoft internal teams
  ADOPTERS.md
Labels: Area - Documentation

#1399 Add PipelineIndentationStyle.None option for scenarios where indentation is custom, inconsistent or the user does not like any of the 3 pipeline indentation styles
  RuleDocumentation/UseConsistentIndentation.md
  Rules/UseConsistentIndentation.cs
  Tests/Rules/UseConsistentIndentation.tests.ps1
Labels: Area - Formatter

#1286 Add DevContainer support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .vscode/extensions.json
Labels: Area - Build

#1386 Fix false positive of AvoidAlias rule for implicit aliasing of Get- commands for the CommandType ExternalScript
  Rules/AvoidAlias.cs
Labels: Issue - Bug
