Repository PowerShell/PSScriptAnalyzer, pull requests merged in 2020-04, with the labels that each got.

#1423 Fix edge case of PSUseConsistentIndentation for non-default value (IncreaseIndentationForFirstPipeline/IncreaseIndentationAfterEveryPipeline)
  Rules/UseConsistentIndentation.cs
  Tests/Rules/UseConsistentIndentation.tests.ps1
Labels: Area - Formatter, Issue - Bug

#1433 Pin major version of Pester to 4 and upgrade Pester version for WMF4 build
  README.md
  build.psm1
  tools/appveyor.psm1
Labels: Area - Build

#1440 Compatibility tests: Use correct test cases object and remove invalid test case
  PSCompatibilityCollector/Tests/UtilityApi.Tests.ps1
Labels: Area - Test

#1445 change term to satisfy policheck requirements
  CHANGELOG.MD
Labels: Area - Build

#1446 Make CompatibilityCollector able to parse a single version String
  PSCompatibilityCollector/Microsoft.PowerShell.CrossCompatibility/Common/PowerShellVersion.cs
  PSCompatibilityCollector/Tests/UtilityApi.Tests.ps1
Labels: Area - CompatibilityRules

#1447 Update Newtonsoft.Json from 12.0.2 to 12.0.3 in Compatibility project as well
  PSCompatibilityCollector/Microsoft.PowerShell.CrossCompatibility/Microsoft.PowerShell.CrossCompatibility.csproj
Labels: Area - Build

#1450 Cleanup csproj files: Remove code duplication for Configuration and entries in Rules project, since it depends on Engine project
  Engine/Engine.csproj
  Rules/Rules.csproj
Labels: Area - Build

#1451 Invoke-Formatter: Skip VariableAnalysis, which is not used by Formatter rules - this yields a 25% performance improvement
  Engine/Formatter.cs
  Engine/ScriptAnalyzer.cs
Labels: Area - Formatter, Area - Performance

#1453 Lazy initialisation of LinkedList in TokenOperations constructor -> 7% performance gain for formatter
  Engine/TokenOperations.cs
Labels: Area - Formatter, Area - Performance, Area - Rules, Breaking Change

#1457 Update Readme with minimum PowerShell Core version being 6.2
  README.md
Labels: Area - Documentation

#1449 CI: Use runtime expression syntax for passing pwsh parameter
  .azure-pipelines-ci/templates/test.yaml
Labels: Area - Build

#1458 Improve performance of UseConsistentIndentation -> 35% speedup for formatter
  Rules/UseConsistentIndentation.cs
Labels: Area - Formatter, Area - Performance

#1461 Improve performance of UseConsistentIndentation even more > another 10% speedup for formatter
  Rules/UseConsistentIndentation.cs
Labels: Area - Formatter, Area - Performance

#1464 Build: Use logging command as a temporary workaround due to billing bug preventing upload of pipeline artefacts
  .azure-pipelines-ci/ci.yaml
Labels: Area - Build

#1463 UseConsistentIndentation: When non-default options are used, cater for the case of a comment between pipe and newline
  Rules/UseConsistentIndentation.cs
  Tests/Rules/UseConsistentIndentation.tests.ps1
Labels: Area - Formatter, Issue - Bug

#1462 Formatter: Recycle parsed AST and tokens in between rule invocations when no correction was applied to improve performance
  Engine/Commands/InvokeScriptAnalyzerCommand.cs
  Engine/Formatter.cs
  Engine/ScriptAnalyzer.cs
  Tests/Engine/LibraryUsage.tests.ps1
Labels: Area - Formatter, Area - Performance, Breaking Change

#1465 Performance: Eliminate Regex overhead in AvoidTrailingWhitespace -> Speedup of 5% (PowerShell 5.1) or 2.5 % (PowerShell 7.1-preview.2)
  Rules/AvoidTrailingWhitespace.cs
Labels: Area - Performance, Area - Rules

#1442 new build scripts for release pipeline
  Tests/Rules/UseCompatibleCommands.Tests.ps1
  build.ps1
  build.psm1
  tools/releaseBuild/AssemblySignConfig.xml
  tools/releaseBuild/CatalogSignConfig.xml
  tools/releaseBuild/CredScan.Suppressions.json
Labels: Area - Build

#1466 Use separate test.yaml files files since param passing of pwsh still doesn't seem to fully work correctly
  .azure-pipelines-ci/ci.yaml
  .azure-pipelines-ci/templates/test-powershell.yaml
  .azure-pipelines-ci/templates/test-pwsh.yaml
Labels: Area - Build

#1448 Changelog for 1.19.0
  CHANGELOG.MD
Labels: Area - Documentation

#1467 Changelog 1.19.0 update
  CHANGELOG.MD
Labels: Area - Documentation
