Repository PowerShell/PSScriptAnalyzer, pull requests merged in 2022-09, with the labels that each got.

#1838 Fix edge case of UseConsistentIndentation where child pipeline is on the same line as hashtable
  Rules/UseConsistentIndentation.cs
  Tests/Rules/UseConsistentIndentation.tests.ps1
Labels: Issue - Bug, Area - Formatter

#1836 Exclude automatic variable FormatEnumerationLimit from analysis by PSAvoidGlobalVars and PSUseDeclaredVarsMoreThanAssignments
  Engine/SpecialVars.cs
Labels: Issue - Enhancement

#1844 (MAINT) Update URLs for site rebrand
  .github/ISSUE_TEMPLATE/config.yml
  CHANGELOG.MD
  PSCompatibilityCollector/Microsoft.PowerShell.CrossCompatibility/Data/Platform/OperatingSystemData.cs
  README.md
  build.psm1
  docs/Cmdlets/Get-ScriptAnalyzerRule.md
  docs/Cmdlets/Invoke-Formatter.md
  docs/Cmdlets/Invoke-ScriptAnalyzer.md
  docs/Rules/ProvideCommentHelp.md
  docs/Rules/ShouldProcess.md
  docs/Rules/UseApprovedVerbs.md
Labels: Area - Documentation

#1846 PSAvoidUsingPositionalParameters: Do not warn on AZ CLI
  Rules/AvoidPositionalParameters.cs
  Tests/Rules/AvoidPositionalParameters.tests.ps1
  docs/Rules/AvoidUsingPositionalParameters.md
Labels: Area - Rules
