Repository PowerShell/PSScriptAnalyzer, pull requests merged in 2024-02, with the labels that each got.

#1962 Remove Appveyor badge from main README
  README.md
Labels: Area - Documentation

#1963 Do not hard code common parameters in module help test any more
  Tests/Engine/ModuleHelp.Tests.ps1
Labels: Area - Test

#1921 PSReviewUnusedParameter: Add CommandsToTraverse option
  Rules/ReviewUnusedParameter.cs
  Tests/Rules/ReviewUnusedParameter.tests.ps1
  docs/Rules/ReviewUnusedParameter.md
Labels: not ready
